# Generated by Django 5.0 on 2024-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
            ],
        ),
    ]
