version: "3"

services:
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: videoflix
    # "/start" is the shell script used to run the service
    command: /start
    env_file:
      - .env
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  celery_worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: videoflix-celery-worker
    command: /start-celeryworker
    volumes:
      - .:/app
    depends_on: [redis]